window.ARCHIVE_INDEX = {
  "generated_at": "2026-04-29T14:55:30+00:00",
  "article_count": 5,
  "articles": [
    {
      "id": "a7794b329a648c84",
      "title": "US Army turns to Ukraine-tested drones to counter Iranian UAV threat",
      "source": "Defense News Unmanned",
      "url": "https://www.defensenews.com/unmanned/2026/04/20/us-army-turns-to-ukraine-tested-drones-to-counter-iranian-uav-threat/",
      "collected_at": "2026-04-29T13:12:17+00:00",
      "updated_at": "2026-04-29T13:12:17+00:00",
      "last_seen": "2026-04-29T13:12:17+00:00",
      "restricted_detail": false,
      "summary_status": "pending_model",
      "folder": "articles/defense-news-unmanned/us-army-turns-to-ukraine-tested-drones-to-counter-iranian-uav-threat-a7794b329a648c84",
      "original_md": "articles/defense-news-unmanned/us-army-turns-to-ukraine-tested-drones-to-counter-iranian-uav-threat-a7794b329a648c84/original.md",
      "summary_zh_md": "articles/defense-news-unmanned/us-army-turns-to-ukraine-tested-drones-to-counter-iranian-uav-threat-a7794b329a648c84/summary.zh.md",
      "image": "articles/defense-news-unmanned/us-army-turns-to-ukraine-tested-drones-to-counter-iranian-uav-threat-a7794b329a648c84/media/image-01-c17f2d276e.png",
      "summary_excerpt": "> 目前尚未偵測到可用的 `GEMINI_API_KEY` 或 Gemini Python 套件，因此先保留待產生狀態。 - 來源：Defense News Unmanned - URL：https://www.defensenews.com/unmanned/2026/04/20/us-army-turns-to-ukraine-tested-drones-to-counter-iranian-uav-threat/ - restricted_detail：`false` 此專案僅保留公開 OSINT 的高層次背景、政策、技術趨勢與戰場觀察；若來源含可操作細節，正式摘要階段不得重述步驟、參數或攻擊流程。"
    },
    {
      "id": "35eb83c3bc2179e2",
      "title": "US Southern Command stands up autonomous unit",
      "source": "Defense News Unmanned",
      "url": "https://www.defensenews.com/news/your-military/2026/04/21/us-southern-command-stands-up-autonomous-unit/",
      "collected_at": "2026-04-29T13:12:06+00:00",
      "updated_at": "2026-04-29T13:12:06+00:00",
      "last_seen": "2026-04-29T13:12:06+00:00",
      "restricted_detail": false,
      "summary_status": "pending_model",
      "folder": "articles/defense-news-unmanned/us-southern-command-stands-up-autonomous-unit-35eb83c3bc2179e2",
      "original_md": "articles/defense-news-unmanned/us-southern-command-stands-up-autonomous-unit-35eb83c3bc2179e2/original.md",
      "summary_zh_md": "articles/defense-news-unmanned/us-southern-command-stands-up-autonomous-unit-35eb83c3bc2179e2/summary.zh.md",
      "image": "articles/defense-news-unmanned/us-southern-command-stands-up-autonomous-unit-35eb83c3bc2179e2/media/image-01-c17f2d276e.png",
      "summary_excerpt": "> 目前尚未偵測到可用的 `GEMINI_API_KEY` 或 Gemini Python 套件，因此先保留待產生狀態。 - 來源：Defense News Unmanned - URL：https://www.defensenews.com/news/your-military/2026/04/21/us-southern-command-stands-up-autonomous-unit/ - restricted_detail：`false` 此專案僅保留公開 OSINT 的高層次背景、政策、技術趨勢與戰場觀察；若來源含可操作細節，正式摘要階段不得重述步驟、參數或攻擊流程。"
    },
    {
      "id": "b8d7d6db70a26e04",
      "title": "Australia awards contracts for counter-drone tech based on lasers, interceptors",
      "source": "Defense News Unmanned",
      "url": "https://www.defensenews.com/global/asia-pacific/2026/04/24/australia-awards-contracts-for-counter-drone-tech-based-on-lasers-interceptors/",
      "collected_at": "2026-04-29T13:11:52+00:00",
      "updated_at": "2026-04-29T13:11:52+00:00",
      "last_seen": "2026-04-29T13:11:52+00:00",
      "restricted_detail": false,
      "summary_status": "pending_model",
      "folder": "articles/defense-news-unmanned/australia-awards-contracts-for-counter-drone-tech-based-on-lasers-inte-b8d7d6db70a26e04",
      "original_md": "articles/defense-news-unmanned/australia-awards-contracts-for-counter-drone-tech-based-on-lasers-inte-b8d7d6db70a26e04/original.md",
      "summary_zh_md": "articles/defense-news-unmanned/australia-awards-contracts-for-counter-drone-tech-based-on-lasers-inte-b8d7d6db70a26e04/summary.zh.md",
      "image": "articles/defense-news-unmanned/australia-awards-contracts-for-counter-drone-tech-based-on-lasers-inte-b8d7d6db70a26e04/media/image-01-c17f2d276e.png",
      "summary_excerpt": "> 目前尚未偵測到可用的 `GEMINI_API_KEY` 或 Gemini Python 套件，因此先保留待產生狀態。 - 來源：Defense News Unmanned - URL：https://www.defensenews.com/global/asia-pacific/2026/04/24/australia-awards-contracts-for-counter-drone-tech-based-on-lasers-interceptors/ - restricted_detail：`false` 此專案僅保留公開 OSINT 的高層次背景、政策、技術趨勢與戰場觀察；若來源含可操作細節，正式摘要階段不得重述步驟、參數或攻擊流程。"
    },
    {
      "id": "5155d118f2625815",
      "title": "Ukraine to field 25,000 ground robots in push to replace soldiers for frontline logistics",
      "source": "Defense News Unmanned",
      "url": "https://www.defensenews.com/unmanned/2026/04/24/ukraine-to-field-25000-ground-robots-in-push-to-replace-soldiers-for-frontline-logistics/",
      "collected_at": "2026-04-29T13:11:42+00:00",
      "updated_at": "2026-04-29T13:11:42+00:00",
      "last_seen": "2026-04-29T13:11:42+00:00",
      "restricted_detail": false,
      "summary_status": "pending_model",
      "folder": "articles/defense-news-unmanned/ukraine-to-field-25-000-ground-robots-in-push-to-replace-soldiers-for-5155d118f2625815",
      "original_md": "articles/defense-news-unmanned/ukraine-to-field-25-000-ground-robots-in-push-to-replace-soldiers-for-5155d118f2625815/original.md",
      "summary_zh_md": "articles/defense-news-unmanned/ukraine-to-field-25-000-ground-robots-in-push-to-replace-soldiers-for-5155d118f2625815/summary.zh.md",
      "image": "articles/defense-news-unmanned/ukraine-to-field-25-000-ground-robots-in-push-to-replace-soldiers-for-5155d118f2625815/media/image-01-c17f2d276e.png",
      "summary_excerpt": "> 目前尚未偵測到可用的 `GEMINI_API_KEY` 或 Gemini Python 套件，因此先保留待產生狀態。 - 來源：Defense News Unmanned - URL：https://www.defensenews.com/unmanned/2026/04/24/ukraine-to-field-25000-ground-robots-in-push-to-replace-soldiers-for-frontline-logistics/ - restricted_detail：`false` 此專案僅保留公開 OSINT 的高層次背景、政策、技術趨勢與戰場觀察；若來源含可操作細節，正式摘要階段不得重述步驟、參數或攻擊流程。"
    },
    {
      "id": "7bc6ef53cdec94c2",
      "title": "US Navy’s unmanned MQ-25A Stingray notches first successful test flight",
      "source": "Defense News Unmanned",
      "url": "https://www.defensenews.com/industry/techwatch/2026/04/27/us-navys-unmanned-mq-25a-stingray-notches-first-successful-test-flight/",
      "collected_at": "2026-04-29T03:04:35+00:00",
      "updated_at": "2026-04-29T13:11:26+00:00",
      "last_seen": "2026-04-29T13:11:26+00:00",
      "restricted_detail": false,
      "summary_status": "pending_model",
      "folder": "articles/defense-news-unmanned/us-navy-s-unmanned-mq-25a-stingray-notches-first-successful-test-fligh-7bc6ef53cdec94c2",
      "original_md": "articles/defense-news-unmanned/us-navy-s-unmanned-mq-25a-stingray-notches-first-successful-test-fligh-7bc6ef53cdec94c2/original.md",
      "summary_zh_md": "articles/defense-news-unmanned/us-navy-s-unmanned-mq-25a-stingray-notches-first-successful-test-fligh-7bc6ef53cdec94c2/summary.zh.md",
      "image": "articles/defense-news-unmanned/us-navy-s-unmanned-mq-25a-stingray-notches-first-successful-test-fligh-7bc6ef53cdec94c2/media/image-01-c17f2d276e.png",
      "summary_excerpt": "> 目前尚未偵測到可用的 `GEMINI_API_KEY` 或 Gemini Python 套件，因此先保留待產生狀態。 - 來源：Defense News Unmanned - URL：https://www.defensenews.com/industry/techwatch/2026/04/27/us-navys-unmanned-mq-25a-stingray-notches-first-successful-test-flight/ - restricted_detail：`false` 此專案僅保留公開 OSINT 的高層次背景、政策、技術趨勢與戰場觀察；若來源含可操作細節，正式摘要階段不得重述步驟、參數或攻擊流程。"
    }
  ]
};
